version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: growup_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - growup-vl:/var/lib/postgresql/data
  app:
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=growup_db
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  growup-vl: